Once a Coherence cluster is running with a gRPC proxy, a client can be configured to connect to it.

=== Add the gRPC Client Dependencies

To create a gRPC client application the Coherence gRPC client module must be added to the project dependencies:

Add the Coherence Micronaut gRPC client module:

dependency:coherence-grpc-client[groupId="io.micronaut.coherence"]

Add the Coherence Java client module for the version of Coherence being used:

dependency:coherence-java-client[groupId="com.oracle.coherence.ce",version="20.12.1"]

=== Configure the Client Sessions

When building a gRPC client application, Coherence resources can be accessed via a link:{coherenceApi}/com/tangosol/net/Session.html[Session], the same as any other Coherence application. The Coherence gRPC Java client allows gRPC client sessions to be configured via system properties. When building a Micronaut gRPC client application, those same configuration properties can be provided via Micronaut configuration. The properties names are in the format `coherence.sessions.<name>.*` where `<name>` is the name of the `Session`. The majority of applications would only require a single `Session` so would configure the default session, that has the name `default`. If an application needs to connect to multiple Coherence gRPC servers then multiple named sessions can be configured.

For example, to make the `default` session a gRPC client session, the property `coherence.sessions.default.type` must be set to `grpc`.

[source,yaml]
.application.yaml
----
coherence:
  sessions:
    default:
      type: grpc
----

to make the `default` session a gRPC client session that connects to the server side session with the scope name `Products`, the property `coherence.sessions.default.scopeName` must be set to `Products`.

[source,yaml]
.application.yaml
----
coherence:
  sessions:
    default:
      type: grpc
      scopeName: Products
----

A gRPC client `Session` requires a gRPC `io.grpc.Channel` to connect to the server. Channels in Coherence gRPC are named, there is a default channel, named `default` that is used by gRPC sessions that do not specify a different channel name. The name of the channel a session should use is set with the `coherence.sessions.<name>.channelName` property. In Micronaut configuration this could be:

For example, if there is a session named `catalog` that will use a channeld named `backend` the configuration might look like this:
[source,yaml]
.application.yaml
----
coherence:
  sessions:
    catalog:
      type: grpc
      channelName: backend
----

There would then be a corresponding channel configuration for the channel named `backend`, see below.

=== Configure gRPC Channels

In Coherence gRPC configuration gRPC channels are named, and each session configuration refers to the named channel that it will use. Channels can be configured via system properties and when using Micronaut these same properties can be configured via Micronaut configuration. The properties names are in the format `coherence.grpc.channels.<name>.*` where `<name>` is the name of the `Channel`

If no configuration is provided then by default all gRPC client sessions will use a channel named `default`. If a channel is not configured then it will connect to `localhost:1408` using plain text (i.e. non-TLS).

For example, the most common properties to configure will be the host and port that the client should connect to. To configure these the application configuration might look like this:

[source,yaml]
.application.yaml
----
coherence:
  grpc:
    channels:
      default:
        host: data.coherence.acme.com
        port: 9099
      catalog:
        host: catalog.coherence.acme.com
        port: 8000

  sessions:
    default:
      type: grpc
      channelName: default
    catalog:
      type: grpc
      channelName: catalog
    orders:
      type: grpc
----

The configuration above configures two named channels, `default` and `catalog`.
The `default` channel will connect to a server on `data.coherence.acme.com:9099`, and the `catalog` channel will connect to a server on `catalog.coherence.acme.com:8000`.

The configuration above then configures three sessions, all have a type of `grpc`. The `default` session is configured to use the `default` channel, and the `catalog` session is configured with a channel name of `catalog`. The `orders` session is configured with a type of `grps` but has no `channelName` specified, so it will use the `default` channel.

See the Coherence gRPC client documentation for details on other properties that can be set to configure channels.


=== Using a gRPC Session

As a full gRPC client example, assume that there is a Coherence cluster running a gRPC proxy on a host name of `customers.coherence.acme.com` port `1408`. The client application will use a gRPC session named `customers` to connect to this cluster.

The configuration might look like this:

[source,yaml]
.application.yaml
----
coherence:
  grpc:
    channels:
      customers:
        host: customers.coherence.acme.com
        port: 1408

  sessions:
    customers:
      type: grpc
      channelName: customers
----

A snippet of application code that uses this configuration could then look like this:

[source,java]
.CustomerController.java
----
@Controller
public class CustomerController {
    @Inject
    public CustomerController(@SessionName("customers") @Name("accounts")
                              NamedMap<String, Product> products) {
        // ToDo:
    }
}
----

The `CustomerController` bean above will have the `NamedMap` named `accounts` injected into its constructor. The `NamedMap` will be from the `customers` Session, which will be a gRPC client session connecting to `customers.coherence.acme.com:1408`.

The application code above is no different to normal Coherence Micronaut code, the only thing that makes it a gRPC client is the configuration.
