To use link:{coherenceHome}[Coherence] as a Micronaut HTTP session store add the `micronaut-coherence-session` dependency:

dependency:coherence-session[groupId="io.micronaut.coherence"]

Also, add a Coherence dependency - either Coherence CE or commercial version:

dependency:coherence[groupId="com.oracle.coherence.ce",version="22.06"]

Enable Coherence sessions via configuration in `application.yml`:

.Enabling Coherence Sessions
[source,yaml]
----
micronaut:
  session:
    http:
      coherence:
        enabled: true
        # Optional: name of the cache that will be used for sessions.
        # By default 'http-sessions' cache will be used.
        cache-name: http-session-cache
----

Coherence cache will be obtained using default Coherence session.

In case that cache is configured to use POF serialization, additional POF configuration for the class `io.micronaut.coherence.httpsession.CoherenceSessionStore$CoherenceHttpSession` has to be added to the POF config. User can pick appropriate value for `type-id`.

[source,xml]
----
    <user-type>
      <type-id>2001</type-id>
      <class-name>io.micronaut.coherence.httpsession.CoherenceSessionStore$CoherenceHttpSession</class-name>
    </user-type>
----
