To use link:{coherenceHome}[Coherence] to store configuration values add following dependencies:

dependency:coherence-distributed-configuration[groupId="io.micronaut.coherence"]


Also, add Coherence dependency - either Coherence CE or commercial version:

dependency:coherence[groupId="com.oracle.coherence.ce",version="22.06"]

and coherence java client:

dependency:coherence-java-client[groupId="com.oracle.coherence.ce",version="22.06"]

To enable support simply add the following configuration to your bootstrap configuration file:

[configuration, title = 'Integrating with Oracle Coherence']
----
micronaut:
  application:
    name: hello-world
  config-client:
    enabled: true

coherence:
  client:
    enabled: true
    host: localhost
    port: 1408
----

- `host` and `port` specify the gRPC configuration

Micronaut will use the configured micronaut.application.name to lookup property sources for the application from Coherence.

.Configuration Resolution Precedence
|===
|Cache|Description

|`application`
|Configuration shared by all applications

|`[APPLICATION_NAME]`
|Application specific configuration

|`application-[ENV_NAME]`
|Configuration shared by all applications for an active environment name

|`[APPLICATION_NAME]-[ENV_NAME]`
|Application specific configuration for an active environment name

|===
