
ValueExtractor binding annotations are normal annotations that are themselves annotated with the link:{api}/io/micronaut/coherence/annotation/ExtractorBinding.html[@ExtractorBinding] meta-annotation.
An extractor binding annotation represents a Coherence link:{coherenceApi}/com/tangosol/util/ValueExtractor.html[ValueExtractor] and is used to specify a `ValueExtractor` in certain injection points, for example a View (CQC), `NamedTopic` `Subscriber` beans, `MapEvent` listeners, etc.

There are three parts to using an extractor binding:

* The extractor binding annotation
* An implementation of a link:{api}/io/micronaut/coherence/ExtractorFactory.html[ExtractorFactory] that is annotated with the extractor binding annotation. This is a factory that produces the required `ValueExtractor`.
* Injection points annotated with the extractor binding annotation.

For example; assume there is a Coherence `NamedMap` with the name `people` that contains `Person` instances for the value.
Among the various properties on the `Person` class is a property called `age`.
Now assume we want to inject a view that uses the `age` property for the value, we would need a `ValueExtractor` that extracts the `age` property.

=== Create the extractor binding annotation

First create a simple annotation, it could be called something like `PersonAge`

snippet::io.micronaut.coherence.docs.extractorbinding.PersonAge[tags="imports,clazz"]
<1> The annotation class is annotated with `@ExtractorBinding`
<2> The annotation name is `PersonAge`

In this case the annotation does not need any other attributes.

[.lang-python]
NOTE: In Python an extractor binding annotation is a function returning a decorator, meta-annotated with `@ExtractorBinding` like the Java annotation type.

=== Create the `ExtractorFactory`

Now create the link:{api}/io/micronaut/coherence/ExtractorFactory.html[ExtractorFactory] implementation that will produce instances of the required `ValueExtractor`.
The generic type arguments of the `ExtractorFactory` are the binding annotation type, the type the extractor is applied to (`Person`) and the type of the extracted value (`Integer`).

snippet::io.micronaut.coherence.docs.extractorbinding.PersonAgeExtractorFactory[tags="imports,clazz"]
<1> The class is annotated with the `PersonAge` extractor binding annotation
<2> The class must be a Micronaut bean, in this case a singleton
<3> The create method uses the Coherence `Extractors` API to create the required extractor, in this case a trivial property extractor.

The parameter to the `create` method is the annotation used on the injection point.
In this case the annotation has no values, but if it did we could access those values to customize how the `ValueExtractor` is created.


=== Annotate the Injection Point

Now the application code where the view is to be injected can use the custom extractor binding annotation.

[.lang-python]
NOTE: Injecting a `NamedMap`, `NamedCache` or view into a Python bean is not supported yet: the Python runtime copies injected Java `Map` values into a plain Python mapping, so the injected object is a snapshot without the `NamedMap` API. Inject a `Session` instead and obtain the map with `session.getMap("people")`; the injection syntax shown below is the intended one.

snippet::io.micronaut.coherence.docs.extractorbinding.PersonAgeView[tags="inject"]
<1> The `@View` annotation indicates that this is a view rather than a plain `NamedMap`
<2> The `@PersonAge` annotation links to the custom extractor factory used to create the `ValueExtractor` for the view
<3> The `@Name` annotation indicates the underlying cache/map name to use for the view
<4> Note that the `NamedMap` generics are now `String` and `Integer` not `String` and `Person` as the `Person` values from the underlying cache are transformed into `Integer` values by extracting just the age property.
