Coherence link:{coherenceApi}/com/tangosol/net/topic/NamedTopic.html[NamedTopic]
instances can be injected as beans in Micronaut applications.

The simplest way to inject a `NamedTopic` is to just annotate the injection point with `@javax.inject.Inject`.

[source,java]
----
@Inject
private NamedTopic<Person> people;
----

In this example the injection point field name is used to determine the topic name to inject,
so a `NamedTopic` bean with an underlying topic name of `people` will be injected.

As an alternative to using a `NamedTopic` directly in code, Coherence Micronaut also supports annotating methods directly as publishers and subscribers using the same approach as Micronaut Messaging. See the <<messagingWithTopics.adoc,Micronaut Messaging with Coherence Topics>> section of the documentation.

== Specify the Topic Name

Sometimes the name of the topic being injected needs to be different to the injection point name.
This is always the case when injecting into method parameters as the parameter names are lost by the time the injection point is processed. In this case we can use the link:{api}/io/micronaut/coherence/annotation/Name.html[@Name]
annotation to specify the underlying cache name.

The example below will inject a `NamedTopic` that uses an underlying topic named `orders`.

[source,java]
----
@Inject
@Name("people")
private NamedTopic<Order> orders;
----

The same applies when injecting a constructor or method parameter:

[source,java]
----
@Singleton
public class SomeBean {
    @Inject
    public SomeBean(@Name("orders") NamedTopic<Order> topic) {
        // ToDo:
    }
}
----

== Specify the Session Name

Whilst most applications probably use a single Coherence link:{coherenceApi}/com/tangosol/net/Session.html[Session] there are uses-cases where an application may
have multiple sessions. In this case, when injecting a `NamedTopic` the specific session can be specified
by annotating the injection point with link:{api}/io/micronaut/coherence/annotation/SessionName.html[@SessionName].

In the previous examples where no `@SessionName` was specified Coherence will use the default session to obtain the caches.

For example, assume the application has multiple sessions configured, one of which is named `Customers`
For example, assume the application has multiple sessions configured, one of which is named `Customers`
the following code snippet injects a `NamedTopic` using an underlying topic named `orders` in the `Customers` session.

[source,java]
----
@Inject
@SessionName("Customers")
@Name("orders")
private NamedTopic<Order> topic;
----

Again, the same annotation can be used on method parameter injection points.

[source,java]
----
@Controller
public class OrderProcessor {
    @Inject
    public OrderProcessor(@SessionName("Customers") @Name("orders")
                          NamedTopic<Order> orders) {
        // ToDo:
    }
}
----
