Sometimes it might not be possible to inject a Coherence resource, such as `NamedMap` or `NamedCache` directly because
the name of the resource to be injected is not known until runtime. In this case it makes sense to inject a
{coherenceApi}com/tangosol/net/Session.html[Session] instance which can then be used to obtain other resources.

The simplest way to inject a `Session` is just to annotate a field, method parameter, or other injection point.

[source,java]
----
@Controller
public class MyBean {
    @Inject
    private Session session;
----

or into a constructor:
[source,java]
----
@Controller
public class MyBean {
    @Inject
    public MyBean(Session session) {
        // ToDo...
    }
}
----

Both examples above will inject the default `Session` instance into the injection point.

== Specify a Session Name

For most applications that only use a single `Session` the simple examples above will be all that is required.
Some applications though may use multiple named `Session` instances, in which case the `Session` name need to
be specified.
This can be done by adding the link:{api}/io/micronaut/coherence/annotation/Name.html[@Name] annotation to the injection point.

[source,java]
----
@Controller
public class MyBean {
    @Inject
    @Name("Catalog")
    private Session session;
----

or into a constructor:
[source,java]
----
@Controller
public class MyBean {
    @Inject
    public MyBean(@Name("Catalog") Session session) {
        // ToDo...
    }
}
----

In both examples above the `Session` injected will be the `Catalog` session.
The named `Session` must have previously been configured when <<bootstrap,bootstrapping Coherence>>.
