In the above configuration, the `coherence` section contains a `sessions` section which is the configuration of one
or more sessions. The format is a map using the session name as the map key. In the above example there is a single session with the name `default`.

In the example below, there are two sessions configured, one named `catalog` and one named `customer`:

[source,yaml]
.application.yaml
----
coherence:
  sessions:
    catalog:
      config: catalog-config.xml
    customer:
      config: customer-config.xml
----

[Note]
====
The `default` session will only exist when zero sessions are specifically configured or the `default` session is specifically configured.

For example, in the configuration below there wil be no `default` session, only a single session named `catalog`.
.application.yaml
----
coherence:
  sessions:
    catalog:
      config: catalog-config.xml
----

In this example, there will be two sessions, one named `catalog` and the `default` session.
.application.yaml
----
coherence:
  sessions:
    catalog:
      config: catalog-config.xml
    default:
      config: coherence-config.xml
----
====
