/**
 * The model classes of the Python documentation examples.
 * <p>
 * TODO(python): they are written in Java because Coherence serializes the values stored in its caches and
 * published to its topics, and the Java classes generated by the Python compiler for Python classes are not
 * {@link java.io.Serializable} (they hold a reference to the GraalPy object). The package is deliberately
 * not a sub-package of the {@code micronaut.coherence.docs} Python package, otherwise the Python import
 * {@code micronaut.coherence.docs.model} would be resolved against the Python package instead of the Java one.
 */
package io.micronaut.coherence.examples.model;
