Whilst most applications probably use a single Coherence link:{coherenceApi}/com/tangosol/net/Session.html[Session] there are uses-cases where an application may
have multiple sessions. In this case, when injecting a `NamedMap` the specific session can be specified
by annotating the injection point with link:{api}/io/micronaut/coherence/annotation/SessionName.html[@SessionName].

In the previous examples where no `@SessionName` was specified Coherence will use the default session to obtain the caches.

Assuming the application has multiple sessions configured, one of which is named `Catalog` the following example
injects a `NamedMap` from an underlying cache named `products` in the `Catalog` session.

[source,java]
----
@Inject
@SessionName("Catalog")
@Name("products")
private NamedMap<String, Product> map;
----

Again, the same annotation can be used on method parameter injection points.
[source,java]
----
@Controller
public class CatalogController {
    @Inject
    public CatalogController(@SessionName("Catalog") @Name("products")
                             NamedMap<String, Product> products) {
        // ToDo:
    }
}
----
