View (or link:{coherenceApi}/com/tangosol/net/ContinuousQueryCache.html[ContinuousQueryCache]) beans can be injected by specifying the
link:{api}/io/micronaut/coherence/annotation/View.html[@View] annotation at the injection point.
A view is a sub-set of the data in an underlying cache, controlled by a link:{coherenceApi}/com/tangosol/util/Filter.html[Filter].

snippet::io.micronaut.coherence.docs.injection.maps.PeopleViews[tags="view"]
<1> The injection point has been annotated with `@View`, so the injected `NamedMap` will actually be an implementation
of a `ContinuousQueryCache`.

In the above example, no `Filter` has been specified, so the default behaviour is to use
an link:{coherenceApi}/com/tangosol/util/filter/AlwaysFilter.html[AlwaysFilter].
This means that the view will contain all the entries from the underlying cache (typically a distributed cache).
As a `ContinuousQueryCache` will hold keys and values locally in deserialized form this can often a better approach
than using a replicated cache.

== Specify a View Filter

Filters are specified for views using a special filter binding annotation.
These are annotations that are themselves annotated with the meta-annotation
link:{api}/io/micronaut/coherence/annotation/FilterBinding.html[@FilterBinding].
The Micronaut Coherence framework comes with some built in implementations, for example
link:{api}/io/micronaut/coherence/annotation/AlwaysFilter.html[@AlwaysFilter],
and link:{api}/io/micronaut/coherence/annotation/WhereFilter.html[@WhereFilter],
and it is simple to implement other as required by applications
(see the <<filterBinding,Filter Binding Annotation>> section for more details).

For example, if there was a cache named "people", containing `Person` instances, and the application required a view
of that cache just containing `People` where the `lastName` attribute is equal to `Simpson` the `@WhereFilter`
filter binding annotation could be used to specify the `Filter`.
The `@WhereFilter` annotation produces a `Filter` created from a Coherence CohQL where clause,
in this case `lastName == 'Simpson'`.

snippet::io.micronaut.coherence.docs.injection.maps.PeopleViews[tags="filter"]

Other built-in or custom filter binding annotations can be used.
Multiple filter-binding annotations can be added to the same injection point to build up more complex
views. The `Filter` instances produced from each filter binding annotation will all be collected together in
an link:{coherenceApi}/com/tangosol/util/filter/AllFilter.html[AllFilter], which will logically AND them together.

For example, combining `@WhereFilter` with the custom `@AdultMales` filter binding annotation created in the
<<filterBinding,Filter Binding Annotation>> section:

snippet::io.micronaut.coherence.docs.injection.maps.PeopleViews[tags="filters"]

The view injected above will be all `People` with a `lastName` attribute equal to `Simpson` that are adult males.
Equivalent to `lastName = 'Simpson' && gender = 'male' && age >= 18`.

== Specify a View Transformer

The values in a view map do not have to be the same as the values in the underlying cache, a link:{coherenceApi}/com/tangosol/util/ValueExtractor.html[ValueExtractor] can be used to transform the actual cache value into a different value in the view.
ValueExtractor are specified for views using a special extractor binding annotation.
These are annotations that are themselves annotated with the meta-annotation
link:{api}/io/micronaut/coherence/annotation/ExtractorBinding.html[@ExtractorBinding].
The Micronaut Coherence framework comes with some built in implementations, for example
link:{api}/io/micronaut/coherence/annotation/PropertyExtractor.html[@PropertyExtractor],
and it is simple to implement other as required by applications
(see the <<valueExtractorBinding,Extractor Binding Annotation>> section for more details).

For example, if there was a cache named "people", containing `Person` instances, and the application required a view where the value was just the `age` attribute of each `Person` rather than the whole cache value. A `@PropertyExtractor` annotation could be used to specify that the values should be transformed using a property extractor.

snippet::io.micronaut.coherence.docs.injection.maps.PeopleViews[tags="extractor"]
<1> The `@View` annotation specifies that a view will be injected rather than a raw `NamedMap`.
<2> The name of the underlying map for the view is `people`.
<3> The `@PropertyExtractor` annotation specifies that a `ValueExtractor` should be used to transform the underlying cache values into different values in the view. In this case the `@PropertyExtractor` annotation will produce a value extractor to extract the `age` property.
<4> Note that the map injected is now a `NamedMap<String, Integer>` with generic types of `String` and `Integer` because the values have been transformed from `Person` to `Integer`.

Multiple extractor bindings can be applied to the injection point, in which case the view value will be a `List` of the extracted attributes.

Custom extractor binding annotations can be created to fulfil more complex transformations.
