To create a topic Publisher that sends messages you can simply define an interface that is annotated with link:{api}/io/micronaut/coherence/annotation/CoherencePublisher.html[`@CoherencePublisher`].

For example the following is a trivial ``@CoherencePublisher`` interface:

snippet::io.micronaut.coherence.docs.messaging.ProductClient[tags="imports,clazz"]

<1> The `@CoherencePublisher` annotation is used to designate this interface as a message publisher.
<2> The `@Topic` annotation indicates which topics the message should be published to
<3> The method defines a single parameter, which is the message value. In this case the values being published are String instances, but they could be any type that can be serialized by Coherence.
<4> It is also possible for the topic to be dynamic by making it a method argument annotated with `@Topic`.

[.lang-python]
NOTE: Python has no method overloading, so the publisher method with the dynamic topic parameter has a distinct name (`send_product_to`).


At compile time Micronaut will produce an implementation of the above interface. You can retrieve an instance of `ProductClient` either by looking up the bean from the `ApplicationContext` or by injecting the bean with `@Inject`:

snippet::io.micronaut.coherence.docs.messaging.MessagingTest[tags="usage"]

Note that since the sendProduct method returns void this means the method will send the message and block until the message has been sent. You can return a `Future` to support non-blocking message delivery.

=== Reactive and Non-Blocking Method Definitions

The `@CoherencePublisher` annotation supports the definition of reactive return types (such as Reactor `Mono` and `Flux`, or any other type convertible to a Reactive Streams `Publisher`) as well as Futures.

The following sections cover possible method signatures and behaviour:

==== Single Value and Return Type

snippet::io.micronaut.coherence.docs.messaging.BookClient[tags="mono"]

The implementation will return a Reactor `Mono` that when subscribed to will subscribe to the passed `Mono` and send the emitted item as a message emitting the item again if successful or an error otherwise.

==== Flux Value and Return Type

snippet::io.micronaut.coherence.docs.messaging.BookClient[tags="flux"]

The implementation will return a Reactor `Flux` that when subscribed to will subscribe to the passed `Flux` and for each emitted item will send a message emitting the item again if successful or an error otherwise.

[.lang-python]
NOTE: In Python the reactive parameters and return types are declared as Reactive Streams `Publisher` type hints, and wrapped with `Mono.from_(...)` / `Flux.from_(...)` when a Reactor operator is needed.

==== Other Reactive Types

Any other reactive type that Micronaut can convert to a Reactive Streams `Publisher` can be used in the same way as `Flux` above.
