To listen to Coherence topic messages you can use the link:{api}/io/micronaut/coherence/annotation/CoherenceTopicListener.html[@CoherenceTopicListener] annotation to define a message listener.

The following example will listen for messages published by the `ProductClient` in the previous section:

[source,java]
.ProductListener.java
----
import io.micronaut.coherence.annotation.CoherenceTopicListener;
import io.micronaut.coherence.annotation.Topic;

@CoherenceTopicListener   // <1>
public class ProductListener {

    @Topic("my-products")   // <2>
    public void receive(String product) { // <3>
        System.out.println("Got Product - " + product);
    }
}
----

<1> The link:{api}/io/micronaut/coherence/annotation/CoherenceTopicListener.html[@CoherenceTopicListener] annotation to indicate that this bean is a Coherence topic listener.
<2> The link:{api}/io/micronaut/coherence/annotation/Topic.html[@Topic] annotation is again used to indicate which topic to subscribe to.
<3> The receive method defines single arguments that will receive the message value, in this case the message is of type `String`.

=== Method Parameter Bindings

When using a Coherence topic link:{coherenceApi}/com/tangosol/net/topic/Subscriber.html[Subscriber] directly in application code, the `receive` method returns an link:{coherenceApi}/com/tangosol/net/topic/Subscriber.Element.html[Element], which contains the message value and metadata. The annotated subscriber method can take various parameter types that will bind to the element itself, the message, or the metadata fields of the element.

For example
[source,java]
----
@CoherenceTopicListener
@Topic("my-products")
public void receive(Element<Product> product) {
    // ... process message ...
}
----

The method above will be passed the link:{coherenceApi}/com/tangosol/net/topic/Subscriber.Element.html[Element] received from the topic. By receiving the element, the method has access to the message value and all the metadata stored with the message.

Alternatively, just select parts of the metadata can be passed as parameters.

|===
|Parameter Name |Parameter Type |Description

|`channel`
|`int` or `Integer`
|The channel in the topic that the message was published to

|`position`
|`com.tangosol.net.topic.Position`,
|The opaque representation of the message's position in the channel in the topic.

|`timestamp`
|`java.time.Instant`, `long` or `Long`
|The time that the message was received on the server

|_any_
|`com.tangosol.net.topic.Subscriber`
|The underlying subscriber the message was received from

|_any_
|`com.tangosol.util.Binary`
|The message value in serialized form. Message values are lazily deserialized in the received element, so if a handler method just needs the serialized form of the message it can be slightly more efficient to take a `Binary` parameter.
|===

NOTE: Some parameters in the table above have fixed parameter names, i.e., `channel`, `position` and `timestamp`. When using these parameters in annotated message handler methods both the parameter name and type must match those in the table above. This is to avoid confusion where the message value type is the same as one of the metadata types where the binding logic would not know what to bind to which parameter. For example, in the unlikely scenario where the message value was just an `int` and the annotated method was soemthing like `public void processMessage(int c, int v)` where `c` is supposed to represent the channel and `v` the value, the binder would not be able to work this out.

=== Committing Messages

An important part of Coherence topic subscribers is committing messages to notify the server that they have been processed and guaranteeing at least once delivery. When using Micronaut Coherence messaging every message will be committed after the handler method has successfully processed the message. This behaviour can be controlled by adding a commit strategy to the link:{api}/io/micronaut/coherence/annotation/CoherenceTopicListener.html[@CoherenceTopicListener] annotation.

==== Default Commit Behaviour

If no `commitStrategy` field has been provided to the `@CoherenceTopicListener` annotation the default behaviour is to synchronously call `Element.commit()` for every message received.

[source,java]
----
@CoherenceTopicListener
@Topic("my-products")
public void receive(Element<Product> product) {
    // ... process message ...
}
----
No `commitStrategy` field has been supplied to the `@CoherenceTopicListener` annotation.

==== Setting Commit Strategy

The link:{api}/io/micronaut/coherence/annotation/CoherenceTopicListener.html[@CoherenceTopicListener] `commitStrategy` field is an enumeration of type link:{api}/io/micronaut/coherence/annotation/CommitStrategy.html[CommitStrategy] with three values, `SYNC`, `ASYNC` and `MANUAL`.

* CommitStrategy.SYNC - This strategy is the default, and will synchronously commit every message upon successful completion of the handler method, by calling `Element.commit()`.

[source,java]
----
@CoherenceTopicListener(commitStrategy = CommitStrategy.SYNC)
@Topic("my-products")
public void receive(Product product) {
    // ... process message ...
}
----

* CommitStrategy.ASYNC - This strategy will asynchronously commit every message upon successful completion of the handler method, by calling `Element.commitAsync()`.

[source,java]
----
@CoherenceTopicListener(commitStrategy = CommitStrategy.ASYNC)
@Topic("my-products")
public void receive(Product product) {
    // ... process message ...
}
----

* CommitStrategy.MANUAL - This strategy will not automatically commit messages, all handling of commits must be done as part of the handler method or by some external process.

[source,java]
----
@CoherenceTopicListener(commitStrategy = CommitStrategy.MANUAL)
@Topic("my-products")
public void receive(Element<Product> product) {
    // ... process message ...

    // manually commit the element
    element.commit();
}
----

In the example above a `MANUAL` commit strategy has used. The element will be committed by the application code at the end of the handler method. To be able to manually commit a message the method must take the `Element` as a parameter so that application code can access the commit methods.
