link:{coherenceApi}com/tangosol/net/events/CoherenceLifecycleEvent.html[CoherenceLifecycleEvents] are emitted to indicate the lifecycle of a link:{coherenceApi}com/tangosol/net/Coherence.html[Coherence] instance.

To subscribe to `CoherenceLifecycleEvent` simply create a Micronaut bean with a listener method annotated with link:{api}/io/micronaut/coherence/annotation/CoherenceEventListener.html[@CoherenceEventListener].
The method should have a single parameter of type `CoherenceLifecycleEvent`.

`CoherenceLifecycleEvent` are emitted by `Coherence` instances and will only be received in the same JVM, which could be a cluster member or a client.

For example, the `onEvent` method below will receive lifecycle events for all `Coherence` instances in the current application:

snippet::io.micronaut.coherence.docs.events.coherenceevents.CoherenceLifecycleListener[tags="all"]

=== Receive Specific CoherenceLifecycleEvent Types

There are four different types of `CoherenceLifecycleEvent`.
By adding the corresponding annotation to the method parameter the method will only receive the specified events.

* Starting - a `Coherence` instance is about to start, use the link:{api}/io/micronaut/coherence/annotation/Starting.html[@Starting] annotation
* Started - a `Coherence` instance has started, use the link:{api}/io/micronaut/coherence/annotation/Started.html[@Started] annotation
* Stopping - a `Coherence` instance is about to stop, use the link:{api}/io/micronaut/coherence/annotation/Stopping.html[@Stopping] annotation
* Stopped - a `Coherence` instance has stopped, use the link:{api}/io/micronaut/coherence/annotation/Stopped.html[@Stopped] annotation

For example, the method below will only receive `Started` and `Stopped` events.

snippet::io.micronaut.coherence.docs.events.coherenceevents.CoherenceLifecycleListener[tags="types"]

=== Receive CoherenceLifecycleEvents for a Specific Coherence Instance

Each `Coherence` instance in an application has a unique name. The observer method can be annotated to only receive events associated with a specific `Coherence` instance by using the link:{api}/io/micronaut/coherence/annotation/Name.html[@Name] annotation.

For example, the method below will only receive events for the `Coherence` instance named `customers`:

snippet::io.micronaut.coherence.docs.events.coherenceevents.CoherenceLifecycleListener[tags="name"]

The method in this example will receive events for the default `Coherence` instance:

snippet::io.micronaut.coherence.docs.events.coherenceevents.CoherenceLifecycleListener[tags="defaultName"]
