An link:{coherenceApi}com/tangosol/net/events/partition/cache/EntryEvent.html[EntryEvent] is emitted when a mutation occurs on an entry in a cache. These events are only emitted on the storage enabled member that is the primary owner of the entry.

To subscribe to `EntryEvent` simply create a Micronaut bean with a listener method annotated with link:{api}/io/micronaut/coherence/annotation/CoherenceEventListener.html[@CoherenceEventListener].
The method should have a single parameter of type `EntryEvent`.

For example, the `onEvent` method below will receive entry events for all caches.

snippet::io.micronaut.coherence.docs.events.coherenceevents.EntryListener[tags="all"]

=== Receive Specific EntryEvent Types

There are a number of different `EntryEvent` types.

* Inserting - an entry is being inserted into a cache, use the link:{api}/io/micronaut/coherence/annotation/Inserting.html[@Inserting] annotation
* Inserted - an entry has been inserted into a cache, use the link:{api}/io/micronaut/coherence/annotation/Inserted.html[@Inserted] annotation
* Updating - an entry is being updated in a cache, use the link:{api}/io/micronaut/coherence/annotation/Updating.html[@Updating] annotation
* Updated - an entry has been updated in a cache, use the link:{api}/io/micronaut/coherence/annotation/Updated.html[@Updated] annotation
* Removing - an entry is being removed from a cache, use the link:{api}/io/micronaut/coherence/annotation/Removing.html[@Removing] annotation
* Removed - an entry has been removed from a cache, use the link:{api}/io/micronaut/coherence/annotation/Removed.html[@Removed] annotation

To restrict the `EntryEvent` types received by a method apply one or more of the annotations above to the method parameter. For example, the method below will receive `Inserted` and `Removed` events.

snippet::io.micronaut.coherence.docs.events.coherenceevents.EntryListener[tags="types"]

[NOTE]
====
The event types fall into two categories, pre-events (those name *ing) and post-events, those named *ed). Pre-events are emitted synchronously before the entry is mutated. Post-events are emitted asynchronously after the entry has been mutated.

As pre-events are synchronous the listener method should not take a long time to execute as it is blocking the cache mutation and could obviously be a performance impact. It is also important that developers understand Coherence reentrancy as the pre-events are executing on the Cache Service thread so cannot call into caches owned by the same service.
====


=== Receive EntryEvents for a Specific NamedMap or NamedCache

To only receive events for a specific `NamedMap` annotate the method parameter with the
link:{api}/io/micronaut/coherence/annotation/MapName.html[@MapName] annotation.
To only receive events for a specific `NamedCache` annotate the method parameter with the
link:{api}/io/micronaut/coherence/annotation/CacheName.html[@CacheName] annotation.

The `@MapName` and `@CacheName` annotations are actually interchangeable so use whichever reads better for your application code, i.e. if your code is dealing with `NamedMap` used `@MapName`. At the storage level, where the events are generated a `NamedMap` and `NamedCache` are the same.

The method below will only receive events for the map named `orders`:

snippet::io.micronaut.coherence.docs.events.coherenceevents.EntryListener[tags="mapName"]

=== Receive EntryEvents from a Specific Cache Service

Caches are owned by a Cache Service, it is possible to restrict events received by a method to only those related to caches owned by a specific service by annotating the method parameter with the
link:{api}/io/micronaut/coherence/annotation/ServiceName.html[@ServiceName] annotation.

The method below will only receive events for the caches owned by the service named `StorageService`:

snippet::io.micronaut.coherence.docs.events.coherenceevents.EntryListener[tags="serviceName"]

=== Receive EntryEvents from a Specific Session

A typical use case is to obtain `NamedCache` and `NamedMap` instances from a `Session`. It is possible to restrict events received by a method to only those related to caches owned by a specific `Session` by annotating the method parameter with the
link:{api}/io/micronaut/coherence/annotation/ScopeName.html[@ScopeName] annotation, specifying the scope name of the `Session`.

The method below will only receive events for the caches owned by the `Session` with the scope name `BackEnd`:

snippet::io.micronaut.coherence.docs.events.coherenceevents.EntryListener[tags="sessionName"]

