A link:{coherenceApi}com/tangosol/net/events/partition/TransactionEvent.html[TransactionEvent] is emitted in relation to all mutations in a single partition in response to executing a single request.
These are commonly referred to as partition level transactions.
For example, an `EntryProcessor` that mutates more than one entry (which could be in multiple caches) as part of a single invocation will cause a partition level transaction to occur encompassing all of those cache entries.

Transaction events are emitted by storage enabled cache services, they will only e received on the same member that the partition level transaction occurred.

To subscribe to `TransactionEvent` simply create a Micronaut bean with a listener method annotated with link:{api}/io/micronaut/coherence/annotation/CoherenceEventListener.html[@CoherenceEventListener].
The method should have a single parameter of type `TransactionEvent`.

For example, the `onEvent` method below will receive all transaction events emitted by storage enabled cache services in the same JVM.

[source,java]
----
@CoherenceEventListener
public void onEvent(TransactionEvent event) {
    // ToDo: process the event
}
----

=== Receive Specific TransactionEvent Types

There are a number of different `TransactionEvent` types.

* Committing - A COMMITTING event is raised prior to any updates to the underlying backing map.
This event will contain all modified entries which may span multiple backing maps. Use the link:{api}/io/micronaut/coherence/annotation/Inserting.html[@Committing] annotation
* Committed - A COMMITTED event is raised after any mutations have been committed to the underlying backing maps.
This event will contain all modified entries which may span multiple backing maps.
Use the link:{api}/io/micronaut/coherence/annotation/Inserted.html[@Committed] annotation

To restrict the `TransactionEvent` types received by a method apply one or more of the annotations above to the method parameter. For example, the method below will receive `Committed` events.

[source,java]
----
@CoherenceEventListener
public void onEvent(@Committed TransactionEvent event) {
    // ToDo: process the event
}
----

=== Receive TransactionEvent from a Specific Cache Service

Caches are owned by a Cache Service, it is possible to restrict events received by a method to only those related to caches owned by a specific service by annotating the method parameter with the
link:{api}/io/micronaut/coherence/annotation/ServiceName.html[@ServiceName] annotation.

The method below will only receive events for the caches owned by the service named `StorageService`:

[source,java]
----
@CoherenceEventListener
public void onEvent(@ServiceName("StorageService") TransactionEvent event) {
    // ToDo: process the event
}
----
