plugins {
    id "io.micronaut.build.internal.coherence-module"
}

dependencies {
    implementation(project(":micronaut-coherence"))
    api(mn.micronaut.inject)
    api(mnCache.micronaut.cache.core)
    compileOnly(libs.managed.coherence)
    testImplementation(libs.managed.coherence)
    testImplementation(mnCache.micronaut.cache.tck)
    testRuntimeOnly(libs.slf4j.simple)
}

