If application code only needs to publish messages to a Coherence `NamedTopic` then instead of injecting a
`NamedTopic` bean, a link:{coherenceApi}/com/tangosol/net/topic/Publisher.html[Publisher] bean can be injected.

The simplest way to inject a `Publisher` is just to annotate the injection point of type `Publisher` with `@Inject`,
for example:

snippet::io.micronaut.coherence.docs.injection.publisher.OrderPublishers[tags="inject"]

The example above will inject a `Publisher` bean, the name of the underlying `NamedTopic` will be taken from the
name of the injection point, in this case `orders`.

== Specify the Topic Name

If the name of the injection point cannot be used as the `NamedTopic` name, which is always the case with injection points that are method or constructor parameters, then the link:{api}/io/micronaut/coherence/annotation/Name.html[@Name] annotation can be used to specify the topic name.

For example, both of the code snippets below inject a `Publisher` that published to the `orders` topic:

snippet::io.micronaut.coherence.docs.injection.publisher.OrderPublishers[tags="name"]

snippet::io.micronaut.coherence.docs.injection.publisher.OrderController[tags="imports,clazz"]

== Specify the Owning Session

As with injection of `NamedTopics`, in applications using multiple `Session` instances, the name of the `Session` that
owns the underlying `NamedTopic` can be specified when injecting a `Publisher` by adding the
link:{api}/io/micronaut/coherence/annotation/SessionName.html[@SessionName] annotation.

snippet::io.micronaut.coherence.docs.injection.publisher.OrderPublishers[tags="session"]
