If application code only needs to subscribe to messages from a Coherence `NamedTopic` then instead of injecting a
`NamedTopic` bean, a link:{coherenceApi}/com/tangosol/net/topic/Subscriber.html[Subscriber] bean can be injected.

The simplest way to inject a `Subscriber` is just to annotate the injection point of type `Subscriber` with `@Inject`,
for example:

[source,java]
----
@Inject
private Subscriber<Order> orders;
----

The example above will inject a `Subscriber` bean, the name of the underlying `NamedTopic` will be taken from the
name of the injection point, in this case `orders`.

== Specify the Topic Name

If the name of the injection point cannot be used as the `NamedTopic` name, which is always the case with injection points that are method or constructor parameters, then the link:{api}/io/micronaut/coherence/annotation/Name.html[@Name] annotation can be used to specify the topic name.

For example, both of the code snippets below inject a `Subscriber` that subscribe to the `orders` topic:

[source,java]
----
@Inject
@Name("orders")
private Subscriber<Order> orders;
----

[source,java]
----
@Controller
public class OrderController {
    @Inject
    public OrderController(@Name("orders") Subscriber<Order> topic) {
        // ToDo:
    }
}
----

== Specify the Owning Session

As with injection of `NamedTopics`, in applications using multiple `Session` instances, the name of the `Session` that
owns the underlying `NamedTopic` can be specified when injecting a `Subscriber` by adding the
link:{api}/io/micronaut/coherence/annotation/SessionName.html[@SessionName] annotation.

[source,java]
----
@Inject
@Name("orders")
@SessionName("Customers")
private Subscriber<Order> orders;
----
